CREATE TABLE "Session" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"organizationId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL UNIQUE,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Invitation" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"email" TEXT NOT NULL,"role" "UserRole" NOT NULL DEFAULT 'MEMBER',"tokenHash" TEXT NOT NULL UNIQUE,"expiresAt" TIMESTAMP(3) NOT NULL,"acceptedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Suppression" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"email" TEXT,"domain" TEXT,"phone" TEXT,"reason" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "CampaignSchedule" ("id" TEXT PRIMARY KEY,"campaignId" TEXT NOT NULL UNIQUE,"cron" TEXT NOT NULL,"timezone" TEXT NOT NULL DEFAULT 'UTC',"active" BOOLEAN NOT NULL DEFAULT true,"nextRunAt" TIMESTAMP(3),"lastRunAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Subscription" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL UNIQUE,"provider" TEXT NOT NULL,"customerId" TEXT,"externalSubscriptionId" TEXT,"priceId" TEXT,"status" TEXT NOT NULL,"currentPeriodEnd" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "WebhookDelivery" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"integrationId" TEXT NOT NULL,"eventType" TEXT NOT NULL,"payload" JSONB NOT NULL,"signature" TEXT,"status" TEXT NOT NULL DEFAULT 'QUEUED',"attempts" INTEGER NOT NULL DEFAULT 0,"responseCode" INTEGER,"error" TEXT,"nextAttemptAt" TIMESTAMP(3),"deliveredAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Invitation" ADD CONSTRAINT "Invitation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Suppression" ADD CONSTRAINT "Suppression_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CampaignSchedule" ADD CONSTRAINT "CampaignSchedule_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WebhookDelivery" ADD CONSTRAINT "WebhookDelivery_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WebhookDelivery" ADD CONSTRAINT "WebhookDelivery_integrationId_fkey" FOREIGN KEY ("integrationId") REFERENCES "Integration"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX "Session_user_org_idx" ON "Session"("userId","organizationId");
CREATE INDEX "Invitation_org_email_idx" ON "Invitation"("organizationId","email");
CREATE INDEX "Suppression_org_email_idx" ON "Suppression"("organizationId","email");
CREATE INDEX "Suppression_org_domain_idx" ON "Suppression"("organizationId","domain");
CREATE INDEX "WebhookDelivery_status_next_idx" ON "WebhookDelivery"("status","nextAttemptAt");
