import Fastify from "fastify";import cors from "@fastify/cors";import helmet from "@fastify/helmet";import rateLimit from "@fastify/rate-limit";import jwt from "@fastify/jwt";import {PrismaClient} from "@prisma/client";import {Queue} from "bullmq";import IORedis from "ioredis";import {randomUUID,createHash} from "node:crypto";import crypto from "node:crypto";import {campaignInputSchema,registerSchema,loginSchema} from "@prospecting/core";import {authContext,hashPassword,verifyPassword,issueToken,requireRole,hashKey,randomToken,tokenHash} from "./auth.js";import {encryptSecret} from "./security.js";
const db=new PrismaClient();const redis=new IORedis(process.env.REDIS_URL||"redis://localhost:6379",{maxRetriesPerRequest:null});const queue=new Queue("prospecting",{connection:redis});const app=Fastify({logger:true,trustProxy:true});
await app.register(helmet);await app.register(cors,{origin:process.env.WEB_ORIGIN||"http://localhost:3000"});await app.register(rateLimit,{max:Number(process.env.RATE_LIMIT_MAX||120),timeWindow:Number(process.env.RATE_LIMIT_WINDOW_MS||60000)});await app.register(jwt,{secret:process.env.JWT_SECRET||"dev-secret-change-me"});
app.setErrorHandler((err,req,reply)=>{const e=err as any;if(e.message==="UNAUTHORIZED"||e.code==="FAST_JWT_EXPIRED"||e.code==="FAST_JWT_INVALID_SIGNATURE"||e.code==="FAST_JWT_MALFORMED")return reply.code(401).send({error:"unauthorized",message:e.code==="FAST_JWT_EXPIRED"?"token_expired":undefined});if(e.message==="FORBIDDEN")return reply.code(403).send({error:"forbidden"});if(e.message==="USAGE_LIMIT")return reply.code(402).send({error:"usage_limit"});req.log.error(e);return reply.code(500).send({error:"internal_error"})});
const audit=async(o:string,u:string,a:string,e?:string,id?:string,m?:unknown,ip?:string)=>db.auditLog.create({data:{id:randomUUID(),organizationId:o,userId:u,action:a,entity:e,entityId:id,metadata:m as any,ip}});
const limits:any={FREE:100,STARTER:1000,GROWTH:10000,PRO:50000,AGENCY:250000,ENTERPRISE:1000000};

function cookie(v:string,maxAge:number){return `prospect_session=${v}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}

async function createSession(userId:string,orgId:string){const raw=randomToken();await db.session.create({data:{id:randomUUID(),userId,organizationId:orgId,tokenHash:tokenHash(raw),expiresAt:new Date(Date.now()+30*86400000)}});return raw}

async function sessionContext(req:any){const h=String(req.headers.cookie||""),m=h.match(/(?:^|;\s*)prospect_session=([^;]+)/);if(!m)throw new Error("UNAUTHORIZED");const s=await db.session.findUnique({where:{tokenHash:tokenHash(m[1])},include:{user:true,organization:true}});if(!s||s.revokedAt||s.expiresAt<new Date())throw new Error("UNAUTHORIZED");const mem=await db.membership.findUnique({where:{userId_organizationId:{userId:s.userId,organizationId:s.organizationId}}});if(!mem)throw new Error("UNAUTHORIZED");return{...mem,user:s.user,organization:s.organization}}

async function enforceUsage(o:string,n:number){const org=await db.organization.findUniqueOrThrow({where:{id:o}});const since=new Date();since.setMonth(since.getMonth()-1);const used=(await db.usageEvent.aggregate({where:{organizationId:o,createdAt:{gte:since}},_sum:{units:true}}))._sum.units||0;if(used+n>limits[org.plan])throw new Error("USAGE_LIMIT");return org}
app.get("/api/health",async()=>({ok:true,version:"0.4.0"}));app.get("/api/ready",async()=>{await db.$queryRaw`SELECT 1`;await redis.ping();return{ok:true}});
app.post("/api/auth/register",async(req,reply)=>{const b=registerSchema.parse(req.body);const email=b.email.toLowerCase();if(await db.user.findUnique({where:{email}}))return reply.code(409).send({error:"email_exists"});const u=await db.user.create({data:{id:randomUUID(),email,name:b.name,passwordHash:await hashPassword(b.password)}});const o=await db.organization.create({data:{id:randomUUID(),name:b.organizationName,plan:"FREE"}});const m=await db.membership.create({data:{id:randomUUID(),userId:u.id,organizationId:o.id,role:"OWNER"}});const token=await issueToken(app,u.id,o.id,m.role),session=await createSession(u.id,o.id);reply.header("Set-Cookie",cookie(session,30*86400));return{token,user:{id:u.id,email:u.email,name:u.name},organization:o}});
app.post("/api/auth/login",async(req,reply)=>{const b=loginSchema.parse(req.body);const u=await db.user.findUnique({where:{email:b.email.toLowerCase()},include:{memberships:{include:{organization:true}}}});if(!u||!(await verifyPassword(b.password,u.passwordHash)))return reply.code(401).send({error:"invalid_credentials"});const m=u.memberships[0];if(!m)return reply.code(403).send({error:"no_membership"});await audit(m.organizationId,u.id,"auth.login",undefined,undefined,undefined,req.ip);const token=await issueToken(app,u.id,m.organizationId,m.role),session=await createSession(u.id,m.organizationId);reply.header("Set-Cookie",cookie(session,30*86400));return{token,user:{id:u.id,email:u.email,name:u.name},organization:m.organization}});
app.post("/api/auth/logout",async(req,reply)=>{const h=String(req.headers.cookie||""),m=h.match(/(?:^|;\s*)prospect_session=([^;]+)/);if(m)await db.session.updateMany({where:{tokenHash:tokenHash(m[1])},data:{revokedAt:new Date()}});reply.header("Set-Cookie",cookie("",0));return{ok:true}});
app.get("/api/auth/me",async(req)=>{try{const m=await sessionContext(req);return{user:{id:m.user.id,email:m.user.email,name:m.user.name},organization:m.organization,role:m.role,auth:"session"}}catch{const m=await authContext(req,db);return{user:{id:m.user.id,email:m.user.email,name:m.user.name},organization:m.organization,role:m.role,auth:"bearer"}}});
app.get("/api/campaigns",async(req)=>{const m=await authContext(req,db);return db.campaign.findMany({where:{organizationId:m.organizationId},orderBy:{createdAt:"desc"}})});
app.post("/api/campaigns",async(req)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN"]);const b=campaignInputSchema.parse(req.body);const c=await db.campaign.create({data:{id:randomUUID(),organizationId:m.organizationId,...b}});await audit(m.organizationId,m.userId,"campaign.create","Campaign",c.id,undefined,req.ip);return c});
app.post("/api/campaigns/:id/run",async(req,reply)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN","MEMBER"]);const c=await db.campaign.findFirst({where:{id:(req.params as any).id,organizationId:m.organizationId}});if(!c)return reply.code(404).send({error:"not_found"});await enforceUsage(m.organizationId,c.maxResults);const j=await db.crawlJob.create({data:{id:randomUUID(),campaignId:c.id}});await db.campaign.update({where:{id:c.id},data:{status:"RUNNING"}});await queue.add("campaign_acquisition",{jobId:j.id,campaignId:c.id,organizationId:m.organizationId},{jobId:j.id,attempts:4,backoff:{type:"exponential",delay:2000},removeOnComplete:100,removeOnFail:200});return{queued:true,jobId:j.id}});
app.post("/api/campaigns/:id/pause",async(req,reply)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN"]);const c=await db.campaign.findFirst({where:{id:(req.params as any).id,organizationId:m.organizationId}});if(!c)return reply.code(404).send({error:"not_found"});await db.campaign.update({where:{id:c.id},data:{status:"PAUSED"}});return{ok:true}});
app.get("/api/leads",async(req)=>{const m=await authContext(req,db),q=req.query as any;return db.business.findMany({where:{organizationId:m.organizationId,...(q.status?{status:q.status}:{}),...(q.search?{OR:[{name:{contains:q.search,mode:"insensitive"}},{domain:{contains:q.search,mode:"insensitive"}}]}:{})},include:{contacts:true,opportunities:true,leadScore:true,research:true},orderBy:{updatedAt:"desc"},take:500})});
app.get("/api/leads/:id",async(req,reply)=>{const m=await authContext(req,db);const b=await db.business.findFirst({where:{id:(req.params as any).id,organizationId:m.organizationId},include:{contacts:true,websiteData:true,evidences:true,opportunities:true,leadScore:true,research:true,syncEvents:true}});if(!b)return reply.code(404).send({error:"not_found"});return b});
app.patch("/api/leads/:id/status",async(req,reply)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN","MEMBER"]);const r=await db.business.updateMany({where:{id:(req.params as any).id,organizationId:m.organizationId},data:{status:(req.body as any).status}});if(!r.count)return reply.code(404).send({error:"not_found"});return{ok:true}});
app.post("/api/leads/:id/research",async(req,reply)=>{const m=await authContext(req,db);const id=(req.params as any).id;if(!await db.business.findFirst({where:{id,organizationId:m.organizationId}}))return reply.code(404).send({error:"not_found"});await queue.add("lead_research",{businessId:id,organizationId:m.organizationId},{attempts:3,backoff:{type:"exponential",delay:1000},removeOnComplete:100});return{queued:true}});
app.get("/api/leads/export.csv",async(req,reply)=>{const m=await authContext(req,db);const rows=await db.business.findMany({where:{organizationId:m.organizationId},include:{contacts:true,leadScore:true,opportunities:true},orderBy:{updatedAt:"desc"}});const esc=(x:unknown)=>`"${String(x??"").replace(/"/g,'""')}"`;const csv=[["name","domain","phone","email","score","status","opportunities"].map(esc).join(","),...rows.map((r:any)=>[r.name,r.domain,r.phone,r.contacts[0]?.email,r.leadScore?.score,r.status,r.opportunities.map((o:any)=>o.title).join(" | ")].map(esc).join(","))].join("\n");reply.header("Content-Type","text/csv").header("Content-Disposition",'attachment; filename="leads.csv"').send(csv)});
app.get("/api/usage",async(req)=>{const m=await authContext(req,db);const since=new Date();since.setMonth(since.getMonth()-1);const used=(await db.usageEvent.aggregate({where:{organizationId:m.organizationId,createdAt:{gte:since}},_sum:{units:true}}))._sum.units||0;return{plan:m.organization.plan,used,limit:limits[m.organization.plan]}});
app.post("/api/api-keys",async(req)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN"]);const secret="aps_"+randomUUID().replaceAll("-","")+randomUUID().replaceAll("-","");const k=await db.apiKey.create({data:{id:randomUUID(),organizationId:m.organizationId,name:String((req.body as any).name||"API Key"),prefix:secret.slice(0,12),keyHash:hashKey(secret)}});return{id:k.id,name:k.name,key:secret}});
app.get("/api/api-keys",async(req)=>{const m=await authContext(req,db);return db.apiKey.findMany({where:{organizationId:m.organizationId},select:{id:true,name:true,prefix:true,lastUsedAt:true,revokedAt:true,createdAt:true},orderBy:{createdAt:"desc"}})});
app.delete("/api/api-keys/:id",async(req,reply)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN"]);const r=await db.apiKey.updateMany({where:{id:(req.params as any).id,organizationId:m.organizationId},data:{revokedAt:new Date()}});if(!r.count)return reply.code(404).send({error:"not_found"});return{ok:true}});
app.post("/api/integrations",async(req)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN"]);const b=req.body as any;const i=await db.integration.create({data:{id:randomUUID(),organizationId:m.organizationId,type:String(b.type||"webhook"),endpoint:String(b.endpoint),secretEncrypted:b.secret?encryptSecret(String(b.secret)):null}});return{id:i.id,type:i.type,endpoint:i.endpoint,active:i.active}});
app.get("/api/audit-logs",async(req)=>{const m=await authContext(req,db);return db.auditLog.findMany({where:{organizationId:m.organizationId},orderBy:{createdAt:"desc"},take:200})});

// Team invitations
app.post("/api/team/invitations",async(req)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN"]);const b=req.body as any;const raw=randomToken();const inv=await db.invitation.create({data:{id:randomUUID(),organizationId:m.organizationId,email:String(b.email).toLowerCase(),role:b.role||"MEMBER",tokenHash:tokenHash(raw),expiresAt:new Date(Date.now()+7*86400000)}});await audit(m.organizationId,m.userId,"team.invite","Invitation",inv.id,{email:inv.email,role:inv.role});return{invitationId:inv.id,token:raw,expiresAt:inv.expiresAt}});
app.get("/api/team/members",async(req)=>{const m=await authContext(req,db);return db.membership.findMany({where:{organizationId:m.organizationId},include:{user:{select:{id:true,name:true,email:true,createdAt:true}}},orderBy:{createdAt:"asc"}})});
app.post("/api/team/invitations/:token/accept",async(req,reply)=>{const raw=(req.params as any).token;const inv=await db.invitation.findUnique({where:{tokenHash:tokenHash(raw)}});if(!inv||inv.acceptedAt||inv.expiresAt<new Date())return reply.code(400).send({error:"invalid_invitation"});const body=req.body as any;let u=await db.user.findUnique({where:{email:String(body.email).toLowerCase()}});if(!u){u=await db.user.create({data:{id:randomUUID(),email:String(body.email).toLowerCase(),name:String(body.name||body.email),passwordHash:await hashPassword(String(body.password))}})}await db.membership.upsert({where:{userId_organizationId:{userId:u.id,organizationId:inv.organizationId}},update:{role:inv.role},create:{id:randomUUID(),userId:u.id,organizationId:inv.organizationId,role:inv.role}});await db.invitation.update({where:{id:inv.id},data:{acceptedAt:new Date()}});return{ok:true}});
app.post("/api/suppressions",async(req)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN","MEMBER"]);const b=req.body as any;const s=await db.suppression.create({data:{id:randomUUID(),organizationId:m.organizationId,email:b.email?String(b.email).toLowerCase():undefined,domain:b.domain?String(b.domain).toLowerCase():undefined,phone:b.phone,reason:String(b.reason||"manual")}});return s});
app.get("/api/suppressions",async(req)=>{const m=await authContext(req,db);return db.suppression.findMany({where:{organizationId:m.organizationId},orderBy:{createdAt:"desc"},take:1000})});
app.delete("/api/suppressions/:id",async(req,reply)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN"]);const r=await db.suppression.deleteMany({where:{id:(req.params as any).id,organizationId:m.organizationId}});if(!r.count)return reply.code(404).send({error:"not_found"});return{ok:true}});
app.post("/api/campaigns/:id/schedule",async(req,reply)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER","ADMIN"]);const id=(req.params as any).id;if(!await db.campaign.findFirst({where:{id,organizationId:m.organizationId}}))return reply.code(404).send({error:"not_found"});const b=req.body as any;return db.campaignSchedule.upsert({where:{campaignId:id},update:{cron:String(b.cron),timezone:String(b.timezone||"UTC"),active:b.active!==false},create:{id:randomUUID(),campaignId:id,cron:String(b.cron),timezone:String(b.timezone||"UTC"),active:b.active!==false}})});
app.delete("/api/campaigns/:id/schedule",async(req,reply)=>{const m=await authContext(req,db);const r=await db.campaignSchedule.deleteMany({where:{campaignId:(req.params as any).id,campaign:{organizationId:m.organizationId}}});if(!r.count)return reply.code(404).send({error:"not_found"});return{ok:true}});
app.get("/api/billing/subscription",async(req)=>{const m=await authContext(req,db);return db.subscription.findUnique({where:{organizationId:m.organizationId}})});
app.post("/api/billing/subscription",async(req)=>{const m=await authContext(req,db);requireRole(m.role,["OWNER"]);const b=req.body as any;return db.subscription.upsert({where:{organizationId:m.organizationId},update:{provider:String(b.provider||"manual"),customerId:b.customerId,externalSubscriptionId:b.externalSubscriptionId,priceId:b.priceId,status:String(b.status||"active"),currentPeriodEnd:b.currentPeriodEnd?new Date(b.currentPeriodEnd):undefined},create:{id:randomUUID(),organizationId:m.organizationId,provider:String(b.provider||"manual"),customerId:b.customerId,externalSubscriptionId:b.externalSubscriptionId,priceId:b.priceId,status:String(b.status||"active"),currentPeriodEnd:b.currentPeriodEnd?new Date(b.currentPeriodEnd):undefined}})});
app.get("/api/providers",async()=>({providers:[{id:"demo",enabled:true},{id:"apify",enabled:!!process.env.APIFY_API_TOKEN}]}));

app.listen({port:Number(process.env.API_PORT||4000),host:"0.0.0.0"}).catch(e=>{app.log.error(e);process.exit(1)});
